# Generated by Django 2.2.7 on 2019-11-25 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(default='', max_length=100)),
                ('visitor_email', models.CharField(default='', max_length=100)),
                ('visitor_phone', models.IntegerField(default=0)),
                ('host_name', models.CharField(default='', max_length=100)),
                ('host_email', models.CharField(default='', max_length=100)),
                ('host_phone', models.IntegerField(default=0)),
                ('time', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
